# Generated by Django 2.2.24 on 2021-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(max_length=500)),
                ('SERIES', models.CharField(max_length=1000, null=True)),
                ('OPEN', models.CharField(max_length=1000, null=True)),
                ('HIGH', models.CharField(max_length=1000, null=True)),
                ('LOW', models.CharField(max_length=1000, null=True)),
                ('CLOSE', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
