# Generated by Django 2.2.24 on 2021-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='TIMESTAMP',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
